name: 'Chromatic Deployment'

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Deploy
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
