name: Publish Package to npmjs
on:
  release:
    types: [published, prereleased]
  workflow_run:
    workflows: [Lint, Test]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@octocat'
      - run: yarn
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
